[package]
name = "clash-verge-service"
version = "0.1.0"
edition = "2021"
authors = ["zzzgydi"]
license = "GPL-3.0"
repository = "https://github.com/zzzgydi/clash-verge-service.git"

[[bin]]
name = "clash-verge-service"
path = "src/main.rs"

[[bin]]
name = "install-service"
path = "src/install.rs"

[[bin]]
name = "uninstall-service"
path = "src/uninstall.rs"

[dependencies]
warp = "0.3"
anyhow = "1.0"
log = "0.4.14"
log4rs = "1.0.0"
once_cell = "1.14"
serde_json = "1.0"
parking_lot = "0.12.0"
windows-service = "0.5.0"
tokio = { version = "1.29.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
