name: Release CI

on: 
  workflow_dispatch:
  push:
      branches:
        - main

jobs:
  release-update:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: |
          rustup default stable-msvc
          cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag_name: latest
          files: |
            target/release/clash-verge-service.exe
            target/release/install-service.exe
            target/release/uninstall-service.exe
